[2022-07-05 07:21:21,274] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T15:00:00+00:00 [queued]>
[2022-07-05 07:21:21,306] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T15:00:00+00:00 [queued]>
[2022-07-05 07:21:21,306] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:21:21,306] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:21:21,307] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:21:21,372] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 15:00:00+00:00
[2022-07-05 07:21:21,383] {standard_task_runner.py:52} INFO - Started process 573 to run task
[2022-07-05 07:21:21,392] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T15:00:00+00:00', '--job-id', '244', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp452duote', '--error-file', '/tmp/tmp463krlgc']
[2022-07-05 07:21:21,393] {standard_task_runner.py:77} INFO - Job 244: Subtask kimuksung_test
[2022-07-05 07:21:21,593] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T15:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:21:21,946] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T15:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T15:00:00+00:00
[2022-07-05 07:21:21,947] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:21:21,949] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:21,990] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T150000, start_date=20220705T072121, end_date=20220705T072121
[2022-07-05 07:21:22,063] {standard_task_runner.py:92} ERROR - Failed to execute job 244 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:22,088] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 07:21:22,249] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:25:33,832] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T15:00:00+00:00 [queued]>
[2022-07-05 07:25:33,929] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T15:00:00+00:00 [queued]>
[2022-07-05 07:25:33,929] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:33,929] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:25:33,930] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:34,058] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 15:00:00+00:00
[2022-07-05 07:25:34,083] {standard_task_runner.py:52} INFO - Started process 763 to run task
[2022-07-05 07:25:34,097] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T15:00:00+00:00', '--job-id', '275', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpcm49cjol', '--error-file', '/tmp/tmp7hegswas']
[2022-07-05 07:25:34,098] {standard_task_runner.py:77} INFO - Job 275: Subtask kimuksung_test
[2022-07-05 07:25:34,398] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T15:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:25:34,613] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T15:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T15:00:00+00:00
[2022-07-05 07:25:34,614] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:25:34,614] {test.py:22} INFO - pubg
[2022-07-05 07:25:34,614] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 07:25:34,679] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T150000, start_date=20220705T072533, end_date=20220705T072534
[2022-07-05 07:25:34,774] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 07:25:34,862] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:05:59,755] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T15:00:00+00:00 [queued]>
[2022-07-05 08:05:59,801] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T15:00:00+00:00 [queued]>
[2022-07-05 08:05:59,801] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:05:59,801] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:05:59,801] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:05:59,865] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 15:00:00+00:00
[2022-07-05 08:05:59,871] {standard_task_runner.py:52} INFO - Started process 2124 to run task
[2022-07-05 08:05:59,922] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T15:00:00+00:00', '--job-id', '319', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp0c8iul7p', '--error-file', '/tmp/tmpt8tzmqd_']
[2022-07-05 08:05:59,953] {standard_task_runner.py:77} INFO - Job 319: Subtask kimuksung_test
[2022-07-05 08:06:00,503] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T15:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:06:01,524] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T15:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T15:00:00+00:00
[2022-07-05 08:06:01,526] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:06:01,526] {test.py:22} INFO - pubg
[2022-07-05 08:06:01,526] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 08:06:02,651] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T150000, start_date=20220705T080559, end_date=20220705T080602
[2022-07-05 08:06:03,452] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:06:04,350] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:11:10,354] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T15:00:00+00:00 [queued]>
[2022-07-05 08:11:10,607] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T15:00:00+00:00 [queued]>
[2022-07-05 08:11:10,607] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:11:10,607] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:11:10,607] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:11:10,714] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 15:00:00+00:00
[2022-07-05 08:11:10,744] {standard_task_runner.py:52} INFO - Started process 2428 to run task
[2022-07-05 08:11:10,765] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T15:00:00+00:00', '--job-id', '384', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpuej9fdt6', '--error-file', '/tmp/tmpzsmjfo4d']
[2022-07-05 08:11:10,766] {standard_task_runner.py:77} INFO - Job 384: Subtask kimuksung_test
[2022-07-05 08:11:11,761] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T15:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:11:12,414] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T15:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T15:00:00+00:00
[2022-07-05 08:11:12,415] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:11:12,416] {test.py:22} INFO - pubg
[2022-07-05 08:11:12,416] {python.py:175} INFO - Done. Returned value was: pubg
[2022-07-05 08:11:12,732] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T150000, start_date=20220705T081110, end_date=20220705T081112
[2022-07-05 08:11:12,881] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:11:13,451] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
