[2022-07-05 07:21:34,884] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T00:00:00+00:00 [queued]>
[2022-07-05 07:21:34,934] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T00:00:00+00:00 [queued]>
[2022-07-05 07:21:34,935] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:21:34,935] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:21:34,936] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:21:35,033] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-05 00:00:00+00:00
[2022-07-05 07:21:35,086] {standard_task_runner.py:52} INFO - Started process 598 to run task
[2022-07-05 07:21:35,107] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-05T00:00:00+00:00', '--job-id', '253', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpac6uw600', '--error-file', '/tmp/tmp2699225x']
[2022-07-05 07:21:35,107] {standard_task_runner.py:77} INFO - Job 253: Subtask kimuksung_test
[2022-07-05 07:21:35,498] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T00:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:21:35,746] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-05T00:00:00+00:00
[2022-07-05 07:21:35,748] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:21:35,749] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:35,799] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220705T000000, start_date=20220705T072134, end_date=20220705T072135
[2022-07-05 07:21:35,842] {standard_task_runner.py:92} ERROR - Failed to execute job 253 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:35,900] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 07:21:36,020] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:25:49,057] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T00:00:00+00:00 [queued]>
[2022-07-05 07:25:49,114] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T00:00:00+00:00 [queued]>
[2022-07-05 07:25:49,115] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:49,115] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:25:49,115] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:49,160] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-05 00:00:00+00:00
[2022-07-05 07:25:49,189] {standard_task_runner.py:52} INFO - Started process 791 to run task
[2022-07-05 07:25:49,208] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-05T00:00:00+00:00', '--job-id', '284', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpmly_5ie1', '--error-file', '/tmp/tmpsaburcl1']
[2022-07-05 07:25:49,209] {standard_task_runner.py:77} INFO - Job 284: Subtask kimuksung_test
[2022-07-05 07:25:49,437] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T00:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:25:49,613] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-05T00:00:00+00:00
[2022-07-05 07:25:49,614] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:25:49,615] {test.py:22} INFO - pubg
[2022-07-05 07:25:49,615] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 07:25:49,739] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220705T000000, start_date=20220705T072549, end_date=20220705T072549
[2022-07-05 07:25:49,808] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 07:25:49,952] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:06:22,591] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T00:00:00+00:00 [queued]>
[2022-07-05 08:06:22,725] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T00:00:00+00:00 [queued]>
[2022-07-05 08:06:22,728] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:06:22,728] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:06:22,728] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:06:22,925] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-05 00:00:00+00:00
[2022-07-05 08:06:22,934] {standard_task_runner.py:52} INFO - Started process 2171 to run task
[2022-07-05 08:06:22,985] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-05T00:00:00+00:00', '--job-id', '338', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpq8kbsk8u', '--error-file', '/tmp/tmplsl9is9n']
[2022-07-05 08:06:22,986] {standard_task_runner.py:77} INFO - Job 338: Subtask kimuksung_test
[2022-07-05 08:06:23,681] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T00:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:06:23,973] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-05T00:00:00+00:00
[2022-07-05 08:06:23,974] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:06:23,974] {test.py:22} INFO - pubg
[2022-07-05 08:06:23,974] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 08:06:24,137] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220705T000000, start_date=20220705T080622, end_date=20220705T080624
[2022-07-05 08:06:24,342] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:06:24,698] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:11:35,993] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T00:00:00+00:00 [queued]>
[2022-07-05 08:11:36,045] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T00:00:00+00:00 [queued]>
[2022-07-05 08:11:36,045] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:11:36,046] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:11:36,046] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:11:36,101] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-05 00:00:00+00:00
[2022-07-05 08:11:36,127] {standard_task_runner.py:52} INFO - Started process 2474 to run task
[2022-07-05 08:11:36,143] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-05T00:00:00+00:00', '--job-id', '404', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp7suoq_lv', '--error-file', '/tmp/tmpxsbbg8sp']
[2022-07-05 08:11:36,144] {standard_task_runner.py:77} INFO - Job 404: Subtask kimuksung_test
[2022-07-05 08:11:36,357] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T00:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:11:36,534] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-05T00:00:00+00:00
[2022-07-05 08:11:36,536] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:11:36,536] {test.py:22} INFO - pubg
[2022-07-05 08:11:36,536] {python.py:175} INFO - Done. Returned value was: pubg
[2022-07-05 08:11:36,589] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220705T000000, start_date=20220705T081135, end_date=20220705T081136
[2022-07-05 08:11:36,661] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:11:36,776] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
