[2022-07-05 07:21:40,665] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T05:00:00+00:00 [queued]>
[2022-07-05 07:21:40,696] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T05:00:00+00:00 [queued]>
[2022-07-05 07:21:40,696] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:21:40,696] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:21:40,697] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:21:40,757] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-05 05:00:00+00:00
[2022-07-05 07:21:40,768] {standard_task_runner.py:52} INFO - Started process 609 to run task
[2022-07-05 07:21:40,775] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-05T05:00:00+00:00', '--job-id', '258', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmppl7ih02h', '--error-file', '/tmp/tmp_s3z4482']
[2022-07-05 07:21:40,779] {standard_task_runner.py:77} INFO - Job 258: Subtask kimuksung_test
[2022-07-05 07:21:41,058] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T05:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:21:41,266] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-05T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-05T05:00:00+00:00
[2022-07-05 07:21:41,271] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:21:41,273] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:41,324] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220705T050000, start_date=20220705T072140, end_date=20220705T072141
[2022-07-05 07:21:41,381] {standard_task_runner.py:92} ERROR - Failed to execute job 258 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:41,412] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 07:21:41,489] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:25:54,464] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T05:00:00+00:00 [queued]>
[2022-07-05 07:25:54,490] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T05:00:00+00:00 [queued]>
[2022-07-05 07:25:54,491] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:54,491] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:25:54,491] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:54,563] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-05 05:00:00+00:00
[2022-07-05 07:25:54,573] {standard_task_runner.py:52} INFO - Started process 801 to run task
[2022-07-05 07:25:54,580] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-05T05:00:00+00:00', '--job-id', '289', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpma9hrnul', '--error-file', '/tmp/tmp45xg8q04']
[2022-07-05 07:25:54,586] {standard_task_runner.py:77} INFO - Job 289: Subtask kimuksung_test
[2022-07-05 07:25:54,726] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T05:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:25:54,877] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-05T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-05T05:00:00+00:00
[2022-07-05 07:25:54,880] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:25:54,881] {test.py:22} INFO - pubg
[2022-07-05 07:25:54,881] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 07:25:54,962] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220705T050000, start_date=20220705T072554, end_date=20220705T072554
[2022-07-05 07:25:55,047] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 07:25:55,103] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:06:34,289] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T05:00:00+00:00 [queued]>
[2022-07-05 08:06:34,328] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T05:00:00+00:00 [queued]>
[2022-07-05 08:06:34,328] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:06:34,329] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:06:34,329] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:06:34,378] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-05 05:00:00+00:00
[2022-07-05 08:06:34,390] {standard_task_runner.py:52} INFO - Started process 2199 to run task
[2022-07-05 08:06:34,413] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-05T05:00:00+00:00', '--job-id', '348', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmphqh32rqc', '--error-file', '/tmp/tmpzbl1zjr9']
[2022-07-05 08:06:34,414] {standard_task_runner.py:77} INFO - Job 348: Subtask kimuksung_test
[2022-07-05 08:06:34,797] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T05:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:06:35,064] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-05T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-05T05:00:00+00:00
[2022-07-05 08:06:35,068] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:06:35,069] {test.py:22} INFO - pubg
[2022-07-05 08:06:35,069] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 08:06:35,186] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220705T050000, start_date=20220705T080634, end_date=20220705T080635
[2022-07-05 08:06:35,363] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:06:35,511] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:11:47,416] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T05:00:00+00:00 [queued]>
[2022-07-05 08:11:47,485] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T05:00:00+00:00 [queued]>
[2022-07-05 08:11:47,485] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:11:47,485] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:11:47,485] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:11:47,576] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-05 05:00:00+00:00
[2022-07-05 08:11:47,584] {standard_task_runner.py:52} INFO - Started process 2501 to run task
[2022-07-05 08:11:47,618] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-05T05:00:00+00:00', '--job-id', '413', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpzrc9mw6f', '--error-file', '/tmp/tmp_qxil53d']
[2022-07-05 08:11:47,619] {standard_task_runner.py:77} INFO - Job 413: Subtask kimuksung_test
[2022-07-05 08:11:47,873] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-05T05:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:11:48,102] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-05T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-05T05:00:00+00:00
[2022-07-05 08:11:48,104] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:11:48,104] {test.py:22} INFO - pubg
[2022-07-05 08:11:48,105] {python.py:175} INFO - Done. Returned value was: pubg
[2022-07-05 08:11:48,176] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220705T050000, start_date=20220705T081147, end_date=20220705T081148
[2022-07-05 08:11:48,231] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:11:48,323] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
