[2022-07-19 06:51:19,394] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator.delete_data_from_table manual__2022-07-19T06:50:56.561772+00:00 [queued]>
[2022-07-19 06:51:19,427] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator.delete_data_from_table manual__2022-07-19T06:50:56.561772+00:00 [queued]>
[2022-07-19 06:51:19,428] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-19 06:51:19,428] {taskinstance.py:1244} INFO - Starting attempt 1 of 6
[2022-07-19 06:51:19,429] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-19 06:51:19,460] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2022-07-19 06:50:56.561772+00:00
[2022-07-19 06:51:19,471] {standard_task_runner.py:52} INFO - Started process 659 to run task
[2022-07-19 06:51:19,491] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator', 'delete_data_from_table', 'manual__2022-07-19T06:50:56.561772+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/example_postgres.py', '--cfg-path', '/tmp/tmppowfo6jx', '--error-file', '/tmp/tmp4suzopbw']
[2022-07-19 06:51:19,492] {standard_task_runner.py:77} INFO - Job 57: Subtask delete_data_from_table
[2022-07-19 06:51:19,651] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_with_postgres_operator.delete_data_from_table manual__2022-07-19T06:50:56.561772+00:00 [running]> on host 0741836b2d3b
[2022-07-19 06:51:19,830] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kimuksung2
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator
AIRFLOW_CTX_TASK_ID=delete_data_from_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-19T06:50:56.561772+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-19T06:50:56.561772+00:00
[2022-07-19 06:51:19,843] {base.py:79} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: test, Login: ***, Password: ***, extra: {}
[2022-07-19 06:51:19,860] {dbapi.py:225} INFO - Running statement: 
            delete from dag_runs where dt = '2022-07-19' and dag_id = 'dag_with_postgres_operator';
        , parameters: None
[2022-07-19 06:51:19,866] {dbapi.py:233} INFO - Rows affected: 1
[2022-07-19 06:51:19,903] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator, task_id=delete_data_from_table, execution_date=20220719T065056, start_date=20220719T065119, end_date=20220719T065119
[2022-07-19 06:51:19,947] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-19 06:51:20,081] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
