[2022-07-19 06:47:17,709] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v02.create_postgres_table scheduled__2022-07-18T00:00:00+00:00 [queued]>
[2022-07-19 06:47:17,762] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v02.create_postgres_table scheduled__2022-07-18T00:00:00+00:00 [queued]>
[2022-07-19 06:47:17,762] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-19 06:47:17,762] {taskinstance.py:1244} INFO - Starting attempt 1 of 6
[2022-07-19 06:47:17,762] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-19 06:47:17,794] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-07-18 00:00:00+00:00
[2022-07-19 06:47:17,799] {standard_task_runner.py:52} INFO - Started process 542 to run task
[2022-07-19 06:47:17,811] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'create_postgres_table', 'scheduled__2022-07-18T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/example_postgres.py', '--cfg-path', '/tmp/tmpks6cydbd', '--error-file', '/tmp/tmpduix2ica']
[2022-07-19 06:47:17,811] {standard_task_runner.py:77} INFO - Job 50: Subtask create_postgres_table
[2022-07-19 06:47:17,918] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.create_postgres_table scheduled__2022-07-18T00:00:00+00:00 [running]> on host 0741836b2d3b
[2022-07-19 06:47:18,034] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kimuksung2
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v02
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-18T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-18T00:00:00+00:00
[2022-07-19 06:47:18,050] {base.py:79} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: test, Login: ***, Password: ***, extra: {}
[2022-07-19 06:47:18,143] {dbapi.py:225} INFO - Running statement: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        , parameters: None
[2022-07-19 06:47:18,155] {postgres.py:73} INFO - NOTICE:  relation "dag_runs" already exists, skipping

[2022-07-19 06:47:18,181] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v02, task_id=create_postgres_table, execution_date=20220718T000000, start_date=20220719T064717, end_date=20220719T064718
[2022-07-19 06:47:18,229] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-19 06:47:18,308] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
